version: '3'

#Docker Networks, create this network if it doesn't exist using `docker network create slack-voter-network`
networks:
  slack-voter-network:
    driver: bridge
    external:
      name: slack-voter-network

services:
  slack-voter-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - "./:/var/www/app"
    ports:
      - "${API_EXTERNAL_PORT}:9000"
    networks:
      - slack-voter-network
    depends_on:
      slack-voter-db:
        condition: service_healthy
    container_name: 'slack-voter-api'
  slack-voter-db:
    image: mysql:5.7
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_EXTERNAL_PORT}:3306"
    networks:
      - slack-voter-network
    container_name: slack-voter-db
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=${MYSQL_ROOT_PASSWORD} --execute \"SHOW DATABASES;\""
      interval: 1s
      retries: 120
